openapi: 3.1.0
info:
  title: api
  version: '1.0'
  summary: Fiubak API
  description: API para comunicarse con los servidores de fiubak
servers:
  - url: $HEROKU_APP.herokuapp.com
paths:
  '/publicaciones/{id publicacion}/informe_cotizacion/':
    post:
      summary: Crear informe para cotización
      operationId: post-cotizacion
      responses:
        '200':
          description: Cotización exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Oferta'
              examples:
                Nueva oferta de cotización:
                  value:
                    id: 7
                    monto: 1840000
                    id_publicacion: 3
                    estado: Pendiente
                    oferente: fiubak
                    id_publicacion_fiubak: null
        '404':
          description: No se encontró la publicación
        '':
          description: ''
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  estetica: Grave
                  neumaticos: Ninguna
                  motor: Ninguna
              properties:
                estetica:
                  type: string
                  enum:
                    - Ninguna
                    - Leve
                    - Grave
                neumaticos:
                  type: string
                  enum:
                    - Ninguna
                    - Leve
                    - Grave
                motor:
                  type: string
                  enum:
                    - Ninguna
                    - Leve
                    - Grave
              required:
                - estetica
                - neumaticos
                - motor
            examples:
              Informe:
                value:
                  estetica: Grave
                  neumaticos: Ninguna
                  motor: Ninguna
          application/xml:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  estetica: Grave
                  neumaticos: Ninguna
                  motor: Ninguna
              properties:
                estetica:
                  type: string
                neumaticos:
                  type: string
                  minLength: 1
                motor:
                  type: string
                  minLength: 1
              required:
                - neumaticos
                - motor
        description: Incluir los elementos para el informe de cotización.
      description: Enviar un informe para cotizar una determinada publicación
      parameters: []
    parameters:
      - schema:
          type: integer
        name: id publicacion
        in: path
        required: true
        description: Id de la publicación sobre la que se envía el informe de cotización
  /:
    get:
      summary: Verificar estado
      tags: []
      responses:
        '200':
          description: Todo OK.
          content:
            text/html:
              schema:
                type: string
              examples:
                'It''s alive! version: 2.3.5':
                  value: string
      operationId: get-status
      description: Permite verificar la versión y si la API está corriendo.
    parameters: []
  /health/:
    get:
      summary: Obtener salud
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: string
                  version:
                    type: string
                required:
                  - status
                  - version
                x-examples:
                  example-1:
                    status: ok
                    version: 2.3.5
              examples:
                Ok:
                  value:
                    status: ok
                    version: 2.3.5
      operationId: get-health
      description: Permite ver en que estado se encuentra y la versión
  /health/version/:
    get:
      summary: Obtener versión
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    version: 2.3.5
                properties:
                  version:
                    type: string
              examples:
                Versión 2.3.5:
                  value:
                    version: 2.3.5
      operationId: get-health-version
      description: ''
components:
  schemas:
    Oferta:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 7
          monto: 1840000
          id_publicacion: 3
          estado: Pendiente
          mail: asd@gmail.com
          oferente: fiubak
          id_publicacion_fiubak: 1
      title: Oferta
      properties:
        id:
          type: number
        monto:
          type: number
        id_publicacion:
          type: number
        estado:
          type: string
          enum:
            - Aceptada
            - Rechazada
            - Pendiente
        mail:
          type: string
          format: email
        oferente:
          type: string
        id_publicacion_fiubak:
          type: number
      required:
        - id
        - monto
        - id_publicacion
        - estado
        - oferente
        - id_publicacion_fiubak
